sudo: required
services:
  - docker

before_install:
  - docker build -t michaelschaidnagel/docker-react -f Dockerfile.dev .

script:
  - docker run michaelschaidnagel/docker-react npm run test -- --coverage
